/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    'getting-started',
    'permissions',
    'examples',
    {
      type: 'category',
      label: 'Command reference',
      link: { type: 'doc', id: 'commands/index' },
      items: [{ type: 'autogenerated', dirName: 'commands' }],
    },
  ],
};

module.exports = sidebars;

